apiVersion: apps/v1
kind: Deployment
metadata:
        name: django-portfolioapp
        labels:
                app: django
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: django
        template:
                metadata:
                        labels:
                                app: django
                spec:
                        containers:
                                - image: abhijeet010797/portfolio-app:latest
                                  name: portfolio-django
                                  ports:
                                          - containerPort: 8000
                                            name: gunicorn
                        imagePullSecrets:
                                - name: regcred
