# Generated by Django 4.0.1 on 2022-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('address', models.CharField(default=None, max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('mail', models.CharField(default=None, max_length=30)),
                ('prof_img', models.ImageField(default=None, upload_to='profile_pic/')),
                ('about', models.TextField(default=None, max_length=500)),
                ('university', models.TextField(default=None, max_length=100)),
                ('degree', models.TextField(default=None, max_length=100)),
                ('degree_specialisations', models.TextField(default=None, max_length=100)),
                ('degree_cgpa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('degree_date', models.DateField()),
                ('intermediate', models.TextField(default=None, max_length=100)),
                ('intermediate_specialisations', models.TextField(default=None, max_length=100)),
                ('intermediate_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('intermediate_date', models.DateField()),
                ('matriculation', models.TextField(default=None, max_length=100)),
                ('matriculation_percentage', models.DecimalField(decimal_places=1, default=8.8, max_digits=2)),
                ('matriculation_date', models.DateField()),
                ('job_profile', models.TextField(default=None, max_length=200)),
                ('organisation', models.TextField(default=None, max_length=200)),
                ('job_description', models.TextField(default=None, max_length=200)),
                ('job_duration', models.TextField(default=None, max_length=200)),
                ('os', models.TextField(default=None, max_length=200)),
                ('language', models.TextField(default=None, max_length=200)),
                ('database', models.TextField(default=None, max_length=200)),
                ('tools', models.TextField(default=None, max_length=200)),
                ('framework', models.TextField(default=None, max_length=200)),
                ('methodology', models.TextField(default=None, max_length=200)),
                ('achievements', models.TextField(default=None, max_length=200)),
            ],
        ),
    ]
