# Generated by Django 4.0.1 on 2022-02-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Database',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Framework',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Language',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Methodology',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Tools',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='os',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
