# Generated by Django 4.0.1 on 2022-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0002_remove_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
