# Generated by Django 4.0.1 on 2022-02-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0002_user_database_user_framework_user_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Database',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Framework',
            new_name='framework',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Methodology',
            new_name='methodology',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tools',
            new_name='tools',
        ),
    ]
