# Generated by Django 4.0.1 on 2022-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0003_rename_database_user_database_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
