# Generated by Django 4.0.1 on 2022-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0004_remove_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='prof_img',
            field=models.ImageField(default=None, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
