# Generated by Django 4.0.1 on 2022-01-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0005_user_mail_user_prof_img_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_img',
            field=models.ImageField(default=None, upload_to='profile_pic/'),
        ),
    ]
